version: '3.8'

services:
  backend:
    build: .
    container_name: store-locator-backend
    ports:
      - "10000:8000"
    volumes:
      - backend-data:/app/backend/data
    restart: always

volumes:
  backend-data:
